services:
  mongo:
    image: mongo:7
    container_name: weather-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: weather-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"   
      - "15672:15672"  
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  backend:
    build: ./backend
    container_name: weather-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/gdash
      - JWT_SECRET=${JWT_SECRET}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  mongo-data: